export const countries = [
  {country: {id: 'AU', flag: 'AU', isd: '+61', currency: 'AUD', currencySymbol: '$', countryName: 'Australia', states: [
    {stateId: 'NSW', stateName: 'New South Wales'},
    {stateId: 'VIC', stateName: 'Victoria'},
    {stateId: 'QLD', stateName: 'Queensland'},
    {stateId: 'SA', stateName: 'South Australia'},
    {stateId: 'WA', stateName: 'Western Australia'},
    {stateId: 'TAS', stateName: 'Tasmania'},
    {stateId: 'NT', stateName: 'Northern Territory'},
    {stateId: 'ACT', stateName: 'Australian Capital Territory'},
    {stateId: 'OTH', stateName: 'Other Territories'}
  ]}},
  {country: {id: 'GB', flag: 'GB', isd: '+44', currency: 'GBP', currencySymbol: '£', countryName: 'United Kingdom', states: [
    {stateId: 'England', stateName: 'England'},
    {stateId: 'Northern-Ireland', stateName: 'Northern Ireland'},
    {stateId: 'Scotland', stateName: 'Scotland'},
    {stateId: 'Wales', stateName: 'Wales'},
  ]}},
  {country: {id: 'IN', flag: 'IN', isd: '+91', currency: 'INR', currencySymbol: '₹', countryName: 'India', states: [
    {stateId: 'AN', stateName: 'Andaman and Nicobar Islands'},
    {stateId: 'AP', stateName: 'Andhra Pradesh'},
    {stateId: 'AR', stateName: 'Arunachal Pradesh'},
    {stateId: 'AS', stateName: 'Assam'},
    {stateId: 'BR', stateName: 'Bihar'},
    {stateId: 'CH', stateName: 'Chandigarh'},
    {stateId: 'CG', stateName: 'Chhattisgarh'},
    {stateId: 'DD', stateName: 'Dadra, Nagar Haveli, Daman and Diu'},
    {stateId: 'DL', stateName: 'Delhi'},
    {stateId: 'GA', stateName: 'Goa'},
    {stateId: 'GJ', stateName: 'Gujarat'},
    {stateId: 'HR', stateName: 'Haryana'},
    {stateId: 'HP', stateName: 'Himachal Pradesh'},
    {stateId: 'JK', stateName: 'Jammu and Kashmir'},
    {stateId: 'JH', stateName: 'Jharkhand'},
    {stateId: 'KA', stateName: 'Karnataka'},
    {stateId: 'KL', stateName: 'Kerala'},
    {stateId: 'LA', stateName: 'Ladakh'},
    {stateId: 'LD', stateName: 'Lakshadweep'},
    {stateId: 'MP', stateName: 'Madhya Pradesh'},
    {stateId: 'MH', stateName: 'Maharashtra'},
    {stateId: 'MN', stateName: 'Manipur'},
    {stateId: 'ML', stateName: 'Meghalaya'},
    {stateId: 'MZ', stateName: 'Mizoram'},
    {stateId: 'NL', stateName: 'Nagaland'},
    {stateId: 'OD', stateName: 'Odisha'},
    {stateId: 'PY', stateName: 'Puducherry'},
    {stateId: 'PB', stateName: 'Punjab'},
    {stateId: 'RJ', stateName: 'Rajasthan'},
    {stateId: 'SK', stateName: 'Sikkim'},
    {stateId: 'TN', stateName: 'Tamil Nadu'},
    {stateId: 'TS', stateName: 'Telangana'},
    {stateId: 'TR', stateName: 'Tripura'},
    {stateId: 'UP', stateName: 'Uttar Pradesh'},
    {stateId: 'UK', stateName: 'Uttarakhand'},
    {stateId: 'WB', stateName: 'West Bengal'}
  ]}},
  {country: {id: 'JP', flag: 'JP', isd: '+81', currency: 'JPY', currencySymbol: '¥', countryName: 'Japan', states: [
    {stateId: 'Hokkaido', stateName: 'Hokkaido'},
    {stateId: 'Tōhoku', stateName: 'Tōhoku'},
    {stateId: 'Kantō', stateName: 'Kantō'},
    {stateId: 'Chūbu', stateName: 'Chūbu'},
    {stateId: 'Kansai', stateName: 'Kansai'},
    {stateId: 'Chūgoku', stateName: 'Chūgoku'},
    {stateId: 'Shikoku', stateName: 'Shikoku'},
    {stateId: 'Kyūshū', stateName: 'Kyūshū'}
  ]}},
  {country: {id: 'US', flag: 'US', isd: '+1', currency: 'USD', currencySymbol: '$', countryName: 'United States', states: [
    {stateId: 'AL', stateName: 'Alabama'},
    {stateId: 'AK', stateName: 'Alaska'},
    {stateId: 'AZ', stateName: 'Arizona'},
    {stateId: 'AR', stateName: 'Arkansas'},
    {stateId: 'CA', stateName: 'California'},
    {stateId: 'CO', stateName: 'Colorado'},
    {stateId: 'CT', stateName: 'Connecticut'},
    {stateId: 'DE', stateName: 'Delaware'},
    {stateId: 'FL', stateName: 'Florida'},
    {stateId: 'GA', stateName: 'Georgia'},
    {stateId: 'HI', stateName: 'Hawaii'},
    {stateId: 'ID', stateName: 'Idaho'},
    {stateId: 'IL', stateName: 'Illinois'},
    {stateId: 'IN', stateName: 'Indiana'},
    {stateId: 'IA', stateName: 'Iowa'},
    {stateId: 'KS', stateName: 'Kansas'},
    {stateId: 'KY', stateName: 'Kentucky'},
    {stateId: 'LA', stateName: 'Louisiana'},
    {stateId: 'ME', stateName: 'Maine'},
    {stateId: 'MD', stateName: 'Maryland'},
    {stateId: 'MA', stateName: 'Massachusetts'},
    {stateId: 'MI', stateName: 'Michigan'},
    {stateId: 'MN', stateName: 'Minnesota'},
    {stateId: 'MS', stateName: 'Mississippi'},
    {stateId: 'MO', stateName: 'Missouri'},
    {stateId: 'MT', stateName: 'Montana'},
    {stateId: 'NE', stateName: 'Nebraska'},
    {stateId: 'NV', stateName: 'Nevada'},
    {stateId: 'NH', stateName: 'New Hampshire'},
    {stateId: 'NJ', stateName: 'New Jersey'},
    {stateId: 'NM', stateName: 'New Mexico'},
    {stateId: 'NY', stateName: 'New York'},
    {stateId: 'NC', stateName: 'North Carolina'},
    {stateId: 'ND', stateName: 'North Dakota'},
    {stateId: 'OH', stateName: 'Ohio'},
    {stateId: 'OK', stateName: 'Oklahoma'},
    {stateId: 'OR', stateName: 'Oregon'},
    {stateId: 'PA', stateName: 'Pennsylvania'},
    {stateId: 'RI', stateName: 'Rhode Island'},
    {stateId: 'SC', stateName: 'South Carolina'},
    {stateId: 'SD', stateName: 'South Dakota'},
    {stateId: 'TN', stateName: 'Tennessee'},
    {stateId: 'TX', stateName: 'Texas'},
    {stateId: 'UT', stateName: 'Utah'},
    {stateId: 'VT', stateName: 'Vermont'},
    {stateId: 'VA', stateName: 'Virginia'},
    {stateId: 'WA', stateName: 'Washington'},
    {stateId: 'WV', stateName: 'West Virginia'},
    {stateId: 'WI', stateName: 'Wisconsin'},
    {stateId: 'WY', stateName: 'Wyoming'},
    {stateId: 'XX', stateName: 'Other'}
  ]}},
  {country: {id: 'INTL', flag: 'None', isd: '', currency: 'USD', currencySymbol: '$', countryName: 'International', states: []}},
]